// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_rr_cds
NumericVector calc_rr_cds(NumericVector outcome, NumericMatrix covars);
RcppExport SEXP _hdps_calc_rr_cds(SEXP outcomeSEXP, SEXP covarsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covars(covarsSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_rr_cds(outcome, covars));
    return rcpp_result_gen;
END_RCPP
}
// colPrevScores
NumericVector colPrevScores(NumericMatrix x);
RcppExport SEXP _hdps_colPrevScores(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colPrevScores(x));
    return rcpp_result_gen;
END_RCPP
}
// colVars
NumericVector colVars(NumericMatrix x);
RcppExport SEXP _hdps_colVars(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colVars(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdps_calc_rr_cds", (DL_FUNC) &_hdps_calc_rr_cds, 2},
    {"_hdps_colPrevScores", (DL_FUNC) &_hdps_colPrevScores, 1},
    {"_hdps_colVars", (DL_FUNC) &_hdps_colVars, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
