# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_rr_cds <- function(outcome, covars) {
    .Call('_hdps_calc_rr_cds', PACKAGE = 'hdps', outcome, covars)
}

colPrevScores <- function(x) {
    .Call('_hdps_colPrevScores', PACKAGE = 'hdps', x)
}

colVars <- function(x) {
    .Call('_hdps_colVars', PACKAGE = 'hdps', x)
}

