# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_rr_cds <- function(outcome, covars) {
    .Call('hdps_calc_rr_cds', PACKAGE = 'hdps', outcome, covars)
}

colPrevScores <- function(x) {
    .Call('hdps_colPrevScores', PACKAGE = 'hdps', x)
}

colVars <- function(x) {
    .Call('hdps_colVars', PACKAGE = 'hdps', x)
}

